#! /bin/sh

betterlockscreen -l dimblur
sxhkd &

bspc monitor -d 1 2 3 4 5 6 7
#bspc monitor -d
#bspc desktop -B

bspc config bottom_padding 13

bspc config border_width         0
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc desktop ^2 -l monocle

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Terminator desktop=^1 follow=on
bspc rule -a Firefox desktop=^2 follow=on
#bspc rule -a Genymotion desktop=^3
bspc rule -a TelegramDesktop desktop=^3
bspc rule -a Subl desktop=^4
bspc rule -a Spotify desktop=^5
bspc rule -a Lmms desktop=^5
bspc rule -a Spyder3 desktop=^4 follow=on
bspc rule -a Gnome-mplayer desktop=^5 state=floating follow=on
bspc rule -a Gedit state=floating
bspc rule -a 
bspc rule -a Viewnior state=floating
bspc rule -a Nautilus state=floating
bspc rule -a File-roller state=floating
#bspc rule -a Gnome-system-monitor state=floating

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config click_to_focus true
bspc config focus_follows_pointer true

bspc config presel_feedback_color \#aaaaaa

xsetroot -cursor_name left_ptr
telegram-desktop &
#feh --bg-fill ~/Pictures/Arch_Linux_2650_small.jpg
feh --bg-fill --randomize ~/.wallpaper/* &
compton --config ~/.compton.conf -b
xrdb -merge ~/.Xdefaults
redshift &
blueberry-tray &
#/home/gamehelp16/allfloat.sh &

polybar main &
nm-applet &
