#!/bin/sh

# key bindings
sxhkd &

# wallpaper
nitrogen --restore &

# launch compton
al-compositor --start &

# panel
sleep 1; al-polybar-session &

# Set some bsp specific stuff
bspc monitor -d 1 2 3 4 5 6

bspc config border_width 2
bspc config window_gap 10
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 32
bspc config left_padding 0

bspc config split_ratio 0.54
bspc config borderless_monocle true
bspc config gapless_monocle true
#bspc config paddingless_monocle true

bspc desktop ^3 -l monocle
bspc desktop ^5 -l monocle

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config click_to_focus true
bspc config focus_follows_pointer true

bspc rule -a thunar desktop='^1' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a Void_Exit_Session state=floating layer=above
bspc rule -a Exit_Session state=floating layer=above

bspc rule -a Firefox desktop=^3 follow=on
bspc rule -a Termite desktop=^1 follow=on
bspc rule -a Geany state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Gsimplecal state=floating
bspc rule -a TelegramDesktop desktop=^4
bspc rule -a Subl desktop=^4
bspc rule -a Spotify desktop=^5
bspc rule -a Spyder3 desktop=^2 follow=on
bspc rule -a Transmission-gtk desktop=^5 state=floating follow=on
bspc rule -a mpv desktop=^5 state=floating follow=on
bspc rule -a Gnome-calculator state=floating
bspc rule -a Blueberry.py state=floating
bspc rule -a audacious desktop=^5 state=floating follow=on
bspc rule -a Thunar state=floating
bspc rule -a Viewnior state=floating#7F7F7F
bspc rule -a File-roller state=floating
bspc rule -a Gnome-system-monitor state=floating

xsetroot -cursor_name left_ptr &
telegram-desktop &
redshift &
blueberry-tray &
xfsettingsd &
xfce4-panel --disable-wm-check
